version: "3.5"

services:
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-server
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
    links:
      - mongo-db
    networks:
      - goodreading-network

  mongo-db:
    image: mongo:latest
    container_name: mongo-server
    environment:
      MONGO_INITDB_DATABASE: demodb  
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - goodreading-network
  
  redis:
    image: redis:6.2-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - goodreading-network
  api:
    build: .
    container_name: goodreading-api
    restart: unless-stopped
    ports:
      - 5000:80
    depends_on: 
      - mongo-db
    networks:
      - goodreading-network

networks: 
    goodreading-network:
      driver: bridge

volumes:
  mongodb_data_container: